# Generated by Django 2.2.7 on 2019-11-11 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_diagnostic_diagnostic_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='created_by',
            field=models.ForeignKey(on_delete='cascade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnostic_for',
            field=models.ForeignKey(on_delete='cascade', to='patients.Patient'),
        ),
    ]
