# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='parent_contact_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='parent_name',
        ),
    ]
